/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/case-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Runs */
        get: operations["get_case_runs_v1_case_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/case-runs/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Run */
        get: operations["get_case_run_v1_case_runs__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/case-runs/{case_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case Run Timeline Route */
        get: operations["get_case_run_timeline_route_v1_case_runs__case_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Investigation */
        post: operations["run_investigation_v1_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playbook-form-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playbook Options */
        get: operations["get_playbook_options_v1_playbook_form_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/playbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Playbooks */
        get: operations["get_playbooks_v1_playbooks_get"];
        put?: never;
        /** Post Playbook */
        post: operations["post_playbook_v1_playbooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CaseRunDetailResponse */
        CaseRunDetailResponse: {
            /** Cognition Records */
            cognition_records?: components["schemas"]["CognitionRecordResponse"][];
            /** Evidence Records */
            evidence_records?: components["schemas"]["EvidenceRecordView"][];
            final_report?: components["schemas"]["FinalReportStoredResponse"] | null;
            /** Hypotheses */
            hypotheses?: components["schemas"]["HypothesisView"][];
            /** Hypothesis Evidence Links */
            hypothesis_evidence_links?: components["schemas"]["HypothesisEvidenceLinkResponse"][];
            /** Mandatory Checks */
            mandatory_checks?: components["schemas"]["MandatoryCheckStateResponse"][];
            summary: components["schemas"]["CaseRunSummaryResponse"];
            /** Task Evidence Links */
            task_evidence_links?: {
                [key: string]: string[];
            };
            /** Task Hypothesis Links */
            task_hypothesis_links?: {
                [key: string]: string[];
            };
            /** Tasks */
            tasks?: components["schemas"]["TaskView"][];
            /** Termination Snapshots */
            termination_snapshots?: components["schemas"]["TerminationSnapshotView"][];
            /** Tool Executions */
            tool_executions?: components["schemas"]["ToolExecutionResponse"][];
            /** Tool Outputs */
            tool_outputs?: components["schemas"]["ToolOutputResponse"][];
        };
        /** CaseRunSummaryResponse */
        CaseRunSummaryResponse: {
            /** Case Class */
            case_class: string;
            /** Case Id */
            case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Loop Count */
            loop_count: number;
            /** Mode */
            mode: string;
            /** Objective */
            objective: string;
            /** Playbook Policy */
            playbook_policy: string;
            /** Status */
            status: string;
            /**
             * Timeout At
             * Format: date-time
             */
            timeout_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CaseRunTimelineResponse */
        CaseRunTimelineResponse: {
            /** Case Id */
            case_id: string;
            /** Events */
            events?: components["schemas"]["CaseTimelineEventResponse"][];
            /** Latest Stop Reason */
            latest_stop_reason?: string | null;
            /** Objective */
            objective: string;
            /** Objective Satisfied */
            objective_satisfied?: boolean | null;
            /** Status */
            status: string;
            /** Unresolved Blockers */
            unresolved_blockers?: string[];
        };
        /** CaseTimelineEventResponse */
        CaseTimelineEventResponse: {
            /** Caused By Event Id */
            caused_by_event_id?: string | null;
            /** Detail */
            detail?: string | null;
            /** Event Id */
            event_id: string;
            event_type: components["schemas"]["CaseTimelineEventType"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** References */
            references?: components["schemas"]["CaseTimelineReferenceResponse"][];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
        };
        /**
         * CaseTimelineEventType
         * @enum {string}
         */
        CaseTimelineEventType: "case_started" | "task_upserted" | "tool_execution" | "evidence_recorded" | "cognition_recorded" | "termination_evaluated" | "final_report_stored";
        /** CaseTimelineReferenceResponse */
        CaseTimelineReferenceResponse: {
            /** Label */
            label?: string | null;
            /** Reference Id */
            reference_id: string;
            /** Reference Type */
            reference_type: string;
        };
        /** CategoryOptionResponse */
        CategoryOptionResponse: {
            /** Category Id */
            category_id: string;
            /** Description */
            description: string;
            /** Required Tool References */
            required_tool_references?: string[];
            /** Suggested Tool References */
            suggested_tool_references?: string[];
        };
        /** CognitionRecordResponse */
        CognitionRecordResponse: {
            /** Decision Action */
            decision_action: string | null;
            /** Decision Reason */
            decision_reason: string | null;
            /** Feedback Drift Score */
            feedback_drift_score: number | null;
            /** Feedback Novelty Score */
            feedback_novelty_score: number | null;
            /** Feedback Reason */
            feedback_reason: string | null;
            /** Feedback Requires Replan */
            feedback_requires_replan: boolean | null;
            /** Insight Text */
            insight_text: string | null;
            /** Linked Evidence Ids */
            linked_evidence_ids?: string[];
            /** Linked Hypothesis Ids */
            linked_hypothesis_ids?: string[];
            /** Record Id */
            record_id: string;
            /** Record Type */
            record_type: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** CompletionCheckStatus */
        CompletionCheckStatus: {
            /** Check Id */
            check_id: string;
            /** Description */
            description: string;
            /** Passed */
            passed: boolean;
            /** Reason */
            reason: string;
        };
        /** CompletionGateStatus */
        CompletionGateStatus: {
            /** Checks */
            checks?: components["schemas"]["CompletionCheckStatus"][];
            /** Passed */
            passed: boolean;
        };
        /** EvidenceRecordView */
        EvidenceRecordView: {
            /** Anomalies */
            anomalies?: string[];
            /** Confidence Impact */
            confidence_impact: number;
            /** Detail Reason */
            detail_reason?: string | null;
            /** Evidence Id */
            evidence_id: string;
            /** Finding Summary */
            finding_summary: string;
            /** Novelty Signal */
            novelty_signal: number;
            /** Original Char Count */
            original_char_count: number;
            /** Raw Output Size Bytes */
            raw_output_size_bytes: number;
            /** Source */
            source: string;
            /** Tool Execution Id */
            tool_execution_id: string;
        };
        /** FinalReportCheckResponse */
        FinalReportCheckResponse: {
            /** Check Id */
            check_id: string;
            /** Description */
            description: string;
            /** Passed */
            passed: boolean;
            /** Reason */
            reason: string;
        };
        /** FinalReportResponse */
        FinalReportResponse: {
            /** Citations */
            citations?: string[];
            completion_gate_status: components["schemas"]["CompletionGateStatus"];
            /** Confidence Label */
            confidence_label: string;
            /** Confidence Score */
            confidence_score: number;
            /** Customer Followups */
            customer_followups?: string[];
            /** Escalation */
            escalation: string | null;
            /** Evidence Ledger Refs */
            evidence_ledger_refs?: string[];
            /** Final Assessment */
            final_assessment: string;
            /** Hypotheses Considered */
            hypotheses_considered?: components["schemas"]["HypothesisView"][];
            /** Internal Support Followups */
            internal_support_followups?: string[];
            /** Objective */
            objective: string;
            termination_snapshot: components["schemas"]["TerminationSnapshotView"];
        };
        /** FinalReportStoredResponse */
        FinalReportStoredResponse: {
            /** Checks */
            checks?: components["schemas"]["FinalReportCheckResponse"][];
            /** Completion Gate Passed */
            completion_gate_passed: boolean;
            /** Confidence Label */
            confidence_label: string;
            /** Confidence Score */
            confidence_score: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Customer Followups */
            customer_followups?: string[];
            /** Escalation */
            escalation: string | null;
            /** Evidence Ids */
            evidence_ids?: string[];
            /** Final Assessment */
            final_assessment: string;
            /** Hypothesis Ids */
            hypothesis_ids?: string[];
            /** Internal Support Followups */
            internal_support_followups?: string[];
            /** Objective */
            objective: string;
            /** Termination Loop Count */
            termination_loop_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** HypothesisEvidenceLinkResponse */
        HypothesisEvidenceLinkResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Id */
            evidence_id: string;
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Relation */
            relation: string;
        };
        /**
         * HypothesisStatus
         * @enum {string}
         */
        HypothesisStatus: "open" | "supported" | "rejected";
        /** HypothesisView */
        HypothesisView: {
            /** Confidence Score */
            confidence_score: number;
            /** Hypothesis Id */
            hypothesis_id: string;
            /**
             * Last Updated At
             * Format: date-time
             */
            last_updated_at: string;
            /** Statement */
            statement: string;
            status: components["schemas"]["HypothesisStatus"];
        };
        /** InvestigationRequest */
        InvestigationRequest: {
            /** @default deep_investigation */
            mode: components["schemas"]["Mode"];
            /** Objective */
            objective: string;
            /** @default suggestive */
            playbook_policy: components["schemas"]["PlaybookPolicy"];
            /**
             * Timeout Minutes
             * @default 120
             */
            timeout_minutes: number;
        };
        /** InvestigationRunResponse */
        InvestigationRunResponse: {
            /** Case Id */
            case_id: string;
            report: components["schemas"]["FinalReportResponse"];
        };
        /** MandatoryCheckStateResponse */
        MandatoryCheckStateResponse: {
            /** Check Id */
            check_id: string;
            /** Description */
            description: string;
            /** Passed */
            passed: boolean | null;
            /** Reason */
            reason: string | null;
        };
        /**
         * Mode
         * @enum {string}
         */
        Mode: "deep_investigation" | "fast_mode";
        /** PlaybookCreateRequest */
        PlaybookCreateRequest: {
            /** Applicable Case Classes */
            applicable_case_classes?: string[];
            /** Created By */
            created_by: string;
            /** Enforcement Mode */
            enforcement_mode: string;
            /** Objective Template */
            objective_template: string;
            /** Playbook Id */
            playbook_id?: string | null;
            /** Status */
            status: string;
            /** Steps */
            steps?: components["schemas"]["PlaybookStepCreateRequest"][];
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /** PlaybookFormOptionsResponse */
        PlaybookFormOptionsResponse: {
            /** Categories */
            categories?: components["schemas"]["CategoryOptionResponse"][];
            /** Enforcement Modes */
            enforcement_modes?: string[];
            /** Failure Actions */
            failure_actions?: string[];
            /** Order Constraints */
            order_constraints?: string[];
            /** Statuses */
            statuses?: string[];
            /** Tools */
            tools?: components["schemas"]["ToolOptionResponse"][];
        };
        /**
         * PlaybookPolicy
         * @enum {string}
         */
        PlaybookPolicy: "mandatory" | "suggestive";
        /** PlaybookStepCreateRequest */
        PlaybookStepCreateRequest: {
            /** Completion Check */
            completion_check: string;
            /** Expected Evidence */
            expected_evidence: string;
            /** Failure Action */
            failure_action: string;
            /** Goal */
            goal: string;
            /** Name */
            name: string;
            /** Order Constraint */
            order_constraint: string;
            /** Preconditions */
            preconditions?: string[];
            /** Required */
            required: boolean;
            /** Step Id */
            step_id: string;
            /** Step Order */
            step_order: number;
            /** Tool Selector */
            tool_selector: string;
        };
        /** PlaybookStepView */
        PlaybookStepView: {
            /** Completion Check */
            completion_check: string;
            /** Expected Evidence */
            expected_evidence: string;
            /** Failure Action */
            failure_action: string;
            /** Goal */
            goal: string;
            /** Name */
            name: string;
            /** Order Constraint */
            order_constraint: string;
            /** Preconditions */
            preconditions?: string[];
            /** Required */
            required: boolean;
            /** Step Id */
            step_id: string;
            /** Tool Selector */
            tool_selector: string;
        };
        /** PlaybookView */
        PlaybookView: {
            /** Applicable Case Classes */
            applicable_case_classes?: string[];
            /** Created By */
            created_by: string;
            /** Enforcement Mode */
            enforcement_mode: string;
            /** Objective Template */
            objective_template: string;
            /** Playbook Id */
            playbook_id: string;
            /** Status */
            status: string;
            /** Steps */
            steps?: components["schemas"]["PlaybookStepView"][];
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "pending" | "in_progress" | "done" | "pruned" | "failed";
        /** TaskView */
        TaskView: {
            /** Created Reason */
            created_reason: string;
            /** Expected Evidence */
            expected_evidence: string;
            /** Expected Information Gain */
            expected_information_gain: number;
            /** Expected Value */
            expected_value: number;
            /** Intent */
            intent: string;
            /** Linked Hypothesis Id */
            linked_hypothesis_id?: string | null;
            /** Priority */
            priority: number;
            status: components["schemas"]["TaskStatus"];
            /** Task Id */
            task_id: string;
            /** Tool Input Evidence Id */
            tool_input_evidence_id?: string | null;
            /** Tool Input Objective */
            tool_input_objective: string;
            /** Tool Input Reason */
            tool_input_reason?: string | null;
            /** Tool Input Step */
            tool_input_step?: string | null;
            /** Tool Name */
            tool_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TerminationSnapshotView */
        TerminationSnapshotView: {
            /** Confidence Sufficient */
            confidence_sufficient: boolean;
            /** Escalation Required */
            escalation_required: boolean;
            /** Evidence Completeness Sufficient */
            evidence_completeness_sufficient: boolean;
            /** Expected Value Below Threshold */
            expected_value_below_threshold: boolean;
            /** Loop Count */
            loop_count: number;
            /** No Novel Signal */
            no_novel_signal: boolean;
            /** Objective Satisfied */
            objective_satisfied: boolean;
            /** Reason */
            reason: string;
            /** Should Stop */
            should_stop: boolean;
            /** Timeout Reached */
            timeout_reached: boolean;
        };
        /** ToolExecutionResponse */
        ToolExecutionResponse: {
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Input Handle */
            input_handle: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Tool Execution Id */
            tool_execution_id: string;
            /** Tool Name */
            tool_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ToolOptionResponse */
        ToolOptionResponse: {
            /** Function Description */
            function_description: string;
            /** Tool Name */
            tool_name: string;
        };
        /** ToolOutputResponse */
        ToolOutputResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Payload Json */
            payload_json: {
                [key: string]: unknown;
            };
            /** Tool Execution Id */
            tool_execution_id: string;
            /** Tool Name */
            tool_name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_case_runs_v1_case_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRunSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_run_v1_case_runs__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_run_timeline_route_v1_case_runs__case_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRunTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_investigation_v1_investigations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestigationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_playbook_options_v1_playbook_form_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybookFormOptionsResponse"];
                };
            };
        };
    };
    get_playbooks_v1_playbooks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybookView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_playbook_v1_playbooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaybookCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaybookView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
