project_id = "eleos-supabase-test"

[api]
enabled = true
port = 3000
schemas = ["public", "auth", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 16

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
jwt_expiry = 3600
enable_signup = true

[storage]
enabled = true
file_size_limit = "50MiB"
